# VERSION 1.0
# AUTHOR:         Javy Liu <javy@leeln.com>
# DESCRIPTION:    leeln base images
# TO_BUILD:       docker build --rm -t leeln/base .
# SOURCE:         https://github.com/leeln/images
FROM alpine:3.4
MAINTAINER Javy Liu <javy@lelen.com>

ENV LANG C.UTF-8

RUN apk upgrade --update && \
    apk add bash