build:
  image: docker.repo.waimai.sankuai.info/docker:dind
  pull: true
  privileged: true
  auth_config:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
  environment:
     - DOCKER_USERNAME=$$DOCKER_USERNAME
     - DOCKER_PASSWORD=$$DOCKER_PASSWORD
  # volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - docker ps
    - docker images
    - docker build -t docker.repo.waimai.sankuai.info/leeln/ubuntu:14.04 ubuntu/14.04
    - docker build -t docker.repo.waimai.sankuai.info/leeln/java:8-jdk java/8/jdk
    - docker build -t docker.repo.waimai.sankuai.info/leeln/java:8-jre java/8/jre
    - docker build -t docker.repo.waimai.sankuai.info/leeln/thrift:0.8.0 thrift/0.8.0

compose:
  dind:
    image: docker:dind
    privileged: true